mystr = "datta is good boy"
print(len(mystr))
print(mystr[: :-2])
print(type(mystr))
print(mystr .isalnum())
print(mystr .isalpha())
print(mystr .endswith("boy"))
print(mystr .endswith("datta"))
print(mystr .count("g"))
print(mystr .count("o"))
print(mystr .count("t"))
print(mystr .capitalize())
print(mystr .find("g"))
print(mystr .lower())
print(mystr .upper())
print(mystr .replace("good","bad"))