grocery = ["Harpic" , 5,"laptop", "Mobile", "sandle"]
print(grocery[4])
numbers = [2 , 5, 7, 99]
print(numbers[3])
print(numbers.sort())
print(numbers[2])
print(numbers[0:2])
print(numbers[ : ])
print(numbers[ : 4: 4])
print(numbers[2 : ])
print(numbers[ : : -1])
print(len(numbers))
print(max(numbers))
print(min(numbers))
numbers.append(5)
numbers.append(5)
numbers.append(5)
numbers.append(5)
numbers.append(5)
print(numbers)
numbers.insert(1,56)
print(numbers)
numbers.remove(99)
print(numbers)
numbers.pop()
print(numbers)